"""ComplianceAssessment model for storing document compliance assessment results."""

from __future__ import annotations
import uuid
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base

class ComplianceAssessment(Base):
    """Record representing a compliance assessment result for a policy document.

    Stores the assessment generated by the document compliance service.
    """

    __tablename__ = "compliance_assessments"

    id: Mapped[uuid.UUID] = mapped_column(postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()"))
    organization_id: Mapped[uuid.UUID] = mapped_column(postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False)
    policy_document_id: Mapped[uuid.UUID] = mapped_column(postgresql.UUID(as_uuid=True), sa.ForeignKey("organization_documents.id"), nullable=False)
    policy_clause_id: Mapped[uuid.UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    regulatory_clause_id: Mapped[uuid.UUID] = mapped_column(postgresql.UUID(as_uuid=True), nullable=False)
    matching_score: Mapped[float] = mapped_column(sa.Float, nullable=False, server_default="0.0")
    compliance_score: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    status: Mapped[str] = mapped_column(sa.String(50), nullable=False)
    explanation: Mapped[str] = mapped_column(sa.Text, nullable=False)
    policy_evidence: Mapped[str] = mapped_column(sa.Text, nullable=False)
    regulatory_requirement: Mapped[str] = mapped_column(sa.Text, nullable=False)
    reasoning_summary: Mapped[str] = mapped_column(sa.Text, nullable=False)
    recommendation: Mapped[str | None] = mapped_column(sa.Text, nullable=True)
    metadata_: Mapped[dict] = mapped_column(postgresql.JSONB, server_default="{}", default=dict)
    analysis_version: Mapped[str] = mapped_column(sa.String(50), nullable=False)
    model_name: Mapped[str] = mapped_column(sa.String(100), nullable=False)
    confidence_score: Mapped[float | None] = mapped_column(sa.Float, nullable=True)
    rank: Mapped[int] = mapped_column(sa.Integer, nullable=False, server_default="1")
    created_at: Mapped[sa.DateTime] = mapped_column(sa.DateTime(timezone=True), server_default=sa.func.now())
    updated_at: Mapped[sa.DateTime] = mapped_column(sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now())
